version: "3"

services:
    
    watchtower:
        container_name: watchtower
        restart: always
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --schedule "0 0 6 * * *" --cleanup
        environment:
            - TZ
    
    mosquitto:
        container_name: mosquitto
        hostname: mosquitto
        image: eclipse-mosquitto
        restart: always
        volumes:
            - ./appdata/mosquitto:/mosquitto/config
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
        environment:
            - TZ
            - PUID
            - PGID
        ports:
            - 1883:1883
            - 9001:9001

    zigbee2mqtt:
        container_name: zigbee2mqtt
        hostname: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        #image: koenkk/zigbee2mqtt:latest-dev  # required for smart plug support
        restart: always
        depends_on:
            - "mosquitto"
        volumes:
            - /run/udev:/run/udev:ro
            #- ./appdata/zigbee2mqtt:/app/data
            - zigbee2mqtt_data:/app/data
            - zigbee2mqtt_log:/app/data/log
            - ./appdata/zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
        devices:
            - /dev/ttyACM0:/dev/ttyACM0
        environment:
            - TZ
            - PUID
            - PGID
        ports:
            - 8080:8080
        privileged: true

    homebridge:
        container_name: homebridge
        hostname: homebridge
        image: oznu/homebridge
        restart: always
        network_mode: host
        volumes:
            - ./appdata/homebridge/config.json:/homebridge/config.json
            - homebridge_data:/homebridge
        environment:
            - TZ
            - PUID
            - PGID
            - HOMEBRIDGE_CONFIG_UI=1
            - HOMEBRIDGE_CONFIG_UI_PORT:8180

volumes:
    mosquitto_data:
    mosquitto_log:
    zigbee2mqtt_data:
    zigbee2mqtt_log:
    homebridge_data:
