homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
  keepalive: 60
  reject_unauthorized: true
  version: 5
  password: mosquitto123
  user: mosquitto
  client_id: zigbee2mqtt
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
advanced:
  channel: 18
  log_level: info
  last_seen: ISO_8601_local
  availability_timeout: 60
experimental:
  output: json
devices:
  '0x000d6ffffefc849c':
    friendly_name: Fireplace Dimmer
    transition: 1
  '0xb0ce1814001af1e2':
    friendly_name: Office Lamp
    transition: 1
  '0xb0ce1814001882cf':
    friendly_name: Desk Lamp
    transition: 1
  '0x5c0272fffece1e75':
    friendly_name: Playroom Light
  '0x5c0272fffecccced':
    friendly_name: Front Porch Light
  '0xb0ce1814001afd21':
    friendly_name: Kitchen Sink Light
    transition: 1
  '0xb0ce1814001afd22':
    friendly_name: Plant Bulb
    transition: 1
  '0xb0ce18140018931d':
    friendly_name: MBR Closet Lamp
    transition: 1
  '0xb0ce1814001b0b8b':
    friendly_name: Living Room Lamp
    transition: 1
  '0x5c0272fffece0cd0':
    friendly_name: Carport Light
  '0x0c4314fffea3925a':
    friendly_name: Carport Motion Sensor
  '0xb0ce18140301dc7b':
    friendly_name: MBR Kylee Lamp
    transition: 1
  '0x5c0272fffece1eb0':
    friendly_name: Flood Light
  '0xcc86ecfffed1a7ce':
    friendly_name: MBR Closet Sensor
  '0xb0ce181403011ff3':
    friendly_name: MBR David Lamp
    transition: 1
groups: {}
blocklist: []
